version: "3"
services:
  sakura-back:
    #image: sakura-back-v1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - PORT=${EXPRESS_PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - DB_URL=${DB_URL}
      - DB_LOGS=${DB_LOGS}
      - REDIS_URL=${REDIS_URL}
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
    volumes:
      - /opt/actions-runner-back/_work/sakura-back/sakura-back:/app
      - /opt/actions-runner-back/_work/sakura-back/sakura-back/images:/app/images
    command: bash -c "npm install && npx prisma generate && npm run build && npm run start"
    ports:
      - "5000:5000"
    networks:
      - local

  postgres:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - local

  redis:
    image: redis:latest
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
    volumes:
      - ./redis/data:/data/
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: >
      --requirepass localpass
    ports:
      - "6379:6379"
    networks:
      - local

networks:
  local:
