name: Deploy to Yandex Cloud
# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [main, deploy-to-yandex-cloud]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Add .env file
        run: rm .env || true && cp .env.example .env

      - run: docker-compose down
      - run: docker-compose —project-name sakura-back up -d —build
      - run: npx prisma migrate deploy
